### ISSUE TITLE
Error when trying grid search

### ISSUE THREAD

**Issue by undefdev** [hanxiao/daanet#2]
Unfortunately training doesn't work for me, I'm getting the following error (abbreviated):

`use config: default_gpu
I:[helper.py:188]:number of jobs in the queue: 1
I:[helper.py:190]:will start the job: python app.py train /tmp/daanet-sb_vvrih ...
use config: default_gpu
I:0:0915-124247:[hel:par:119]:loading parameters...
I:0:0915-124247:[hel:par:128]:[add from /tmp/daanet-hfxaocgi]            task_name:                  qag
I:0:0915-124247:[hel:par:128]:[add from /tmp/daanet-hfxaocgi]          train_files: ['./sample_data/sample.json']
I:0:0915-124247:[hel:par:128]:[add from /tmp/daanet-hfxaocgi]            dev_files: ['./sample_data/sample.json']
I:0:0915-124247:[hel:par:128]:[add from /tmp/daanet-hfxaocgi]           test_files: ['./sample_data/sample.json']
I:0:0915-124247:[hel:par:128]:[add from /tmp/daanet-hfxaocgi] word_embedding_files: ['./sample_data/sample.embed.txt']
I:0:0915-124247:[hel:par:128]:[add from /tmp/daanet-hfxaocgi] char_embedding_files: ['./sample_data/sample.charembed.txt']
I:0:0915-124247:[hel:par:128]:[add from /tmp/daanet-hfxaocgi]           result_dir: ./sample_data/result
Traceback (most recent call last):
  File "app.py", line 15, in <module>
    run()
  File "app.py", line 10, in run
    args = parse_args(sys.argv[2] if len(sys.argv) > 2 else None, MODEL_ID, CONFIG_SET, followup_args)
  File "/home/undef/readingComprehension/daanet/utils/helper.py", line 148, in parse_args
    shutil.copytree('./', hparams.get('code_dir'), ignore=shutil.ignore_patterns(*IGNORE_PATTERNS))
  File "/home/undef/readingComprehension/daanet/env/lib/python3.6/shutil.py", line 359, in copytree
    raise Error(errors)
shutil.Error: [('./save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020205/code/save/0915-020...`

**Comment by EllaDing** [comment]
I set the model_dir to '' and then the problem above disappeared. But I got another error: ModuleNotFoundError: No module named 'dataio'

It seems like this dataio is different from the package dataIO... Is there some instruction to install it?

**Comment by hanxiao** [comment]
Please change your yaml setting to:
```yaml
  package_dataio: dataio_utils.full_load_io
```

there is no need to install any "dataIO" package. there is no such thing like that.

**Comment by alekzieba** [comment]
Thank you for your response.  I can confirm that both of the above fixes work for the respective errors, but now I'm getting a new error:
```
...
I:0:1027-182128:[hel:par:166]:           task_name = qag                 
I:0:1027-182128:[hel:par:166]:          test_files = ['./sample_data/sample.json']
I:0:1027-182128:[hel:par:166]:         train_files = ['./sample_data/sample.json']
I:0:1027-182128:[hel:par:166]:    use_answer_masks = True                
I:0:1027-182128:[hel:par:166]:        use_coverage = True                
I:0:1027-182128:[hel:par:166]:            use_oovs = True                
I:0:1027-182128:[hel:par:166]:        weight_decay = 0                   
I:0:1027-182128:[hel:par:166]:word_embedding_files = ['./sample_data/sample.embed.txt']
I:0:1027-182128:[voc:loa: 87]:loading word embedding from ./sample_data/sample.embed.txt
I:0:1027-182128:[voc:loa:108]:building token-id map...
I:0:1027-182128:[voc:loa:130]:size of embedding 1004 x 256
I:0:1027-182128:[voc:loa:132]:size of pretrain embedding 1000 x 256
Traceback (most recent call last):
  File "app.py", line 15, in <module>
    run()
  File "app.py", line 11, in run
    getattr(__import__('api'), sys.argv[1])(args)
  File "/home/alek/Desktop/daanet-env/daanet-2/api.py", line 15, in train
    model = build_model(args)
  File "/home/alek/Desktop/daanet-env/daanet-2/utils/helper.py", line 323, in build_model
    return rccore.RCCore(args)
  File "/home/alek/Desktop/daanet-env/daanet-2/daanet/basic.py", line 24, in __init__
    super().__init__(args)
  File "/home/alek/Desktop/daanet-env/daanet-2/daanet/base.py", line 16, in __init__
    super().__init__(args)
  File "/home/alek/Desktop/daanet-env/daanet-2/base/base_model.py", line 30, in __init__
    self.data_io = dataio.DataIO(args)
  File "/home/alek/Desktop/daanet-env/daanet-2/dataio_utils/full_load_io.py", line 14, in __init__
    ModeKeys.TRAIN: self.load_data(self.args.train_files, ModeKeys.TRAIN),
  File "/home/alek/Desktop/daanet-env/daanet-2/base/base_io.py", line 23, in load_data
    raise NotImplementedError
NotImplementedError
```
